apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    tier: backend
    type: http
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: backend
        type: http
    spec:
      containers:
        - name: {{ .Values.image.repository }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            limits:
              memory: {{ .Values.memory }}
              cpu: {{ .Values.cpu }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheck.endpoint }}
              port: {{ .Values.healthcheck.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path:  {{ .Values.healthcheck.endpoint }}
              port: {{ .Values.healthcheck.port }}
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            failureThreshold: 2